- name: Disabling swarm
  become: yes
  command: docker swarm leave -f
  ignore_errors: yes
  tags: [dockermanager]
  
- name: initialize swarm cluster
  become: yes
  command: docker swarm init -advertise-addr={{ swarm_iface | default('ethO') }}:2377
  register: bootstrap_first_node
  tags: [dockermanager]

